### ISSUE TITLE
When soft keyboard showing， FPDF library is destoryed!

### ISSUE THREAD

**Issue by lgst** [arnaudelub/flutter_fullpdfview#2]
This is log:
D/jniPdfium( 9858): Destroy FPDF library

**Comment by arnaudelub** [comment]
Hi, i'll need more info as it's working fine for me

**Comment by AmanMulani** [comment]
I have used a text input field to jump to the page number given by the user. But as soon as the keyboard is displayed, the pdf view ends abruptly, with log: Destroy FPDF library

**Comment by khlewesamer** [comment]
hi there , and thanx for this plugin , i solve ther problim by add resizeToAvoidBottomPadding: false in Scafold()
, i hope that help you :)

**Comment by wgerez** [comment]
> hi there , and thanx for this plugin , i solve ther problim by add resizeToAvoidBottomPadding: false in Scafold()
> , i hope that help you :)

Now is resizeToAvoidBottomInset: false, "resizeToAvoidBottomPadding" is deprecated

**Comment by Shubham-Phatale** [comment]
> 
> 
> I have used a text input field to jump to the page number given by the user. But as soon as the keyboard is displayed, the pdf view ends abruptly, with log: Destroy FPDF library

Having same issue, is there any solution to this

**Comment by Masrafi** [comment]
I face same kind of problem. Please help me. Here is my problem:


I/flutter ( 2458): tenderimage/Dec08/Dec08_Dhaka Navy-7A.pdf
W/PlatformViewsController( 2458): Creating a virtual display of size: [1440, 3500] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1440, 2701].
D/com.shockwave.pdfium.PdfiumCore( 2458): Starting PdfiumAndroid 1.9.0

D/jniPdfium( 2458): Init FPDF library
D/jniPdfium( 2458): Destroy FPDF library

**Comment by arnaudelub** [comment]
hi, thanks for your feedback.
@Shubham-Phatale , have you tried to use 
```dart
resizeToAvoidBottominset: false
```
?

@Masrafi 
you are trying to creating a virtual display larger then the device size as mention in the error, maybe you should try to fix this.

Feel free to give code sample if you need more help!

**Comment by Masrafi** [comment]
My code is here. To get json data:

getData() async {
    var url = "https://bdtender.com/api/tend_call.php";
    var response = await http.post(url, body: {"id": widget.masrafi});
    Map<String, dynamic> map = jsonDecode(response.body);
    List<dynamic> data = map["data"];
    print(map['image'][0]['img1']);

    var dir = await getTemporaryDirectory();
    File file = new File(dir.path + "map['image'][0]['img1']");
    await file.writeAsBytes(response.bodyBytes, flush: true);
    return file.path;
  } 


And code:
 ListView(
          children: [
            RaisedButton(
              child: Text("Show Please Allah"),
              onPressed: () {
                getData().then((value) {
                  setState(() {
                    _localFile = value;
                  });
                });
              },
            ),
            _localFile != null
                ? Container(
                    height: 1000,
                    width: 500,
                    child: PDFView(
                      filePath: _localFile,
                    ),
                  )
                : CircularProgressIndicator()
          ],
        ))

My Pdf file show console successfully. But when I want to show it in my app it create problem.

**Comment by matheuskildere** [comment]
> Olá, obrigado por este plugin, resolvo o problema adicionando resizeToAvoidBottomPadding: false no Scafold ()
> , espero que ajude você :)

thanks man

**Comment by Mohammad-Adam** [comment]
this worked for me: https://stackoverflow.com/a/60246126/12595823

**Comment by ukbaranwal31** [comment]
It can be reproduced easily by simply reloading the app, just press Command+s, or type r in terminal...
