### ISSUE TITLE
swipeHorizontal  true  persists on IOS even when set to false. i want vertical scroll only

### ISSUE THREAD

**Issue by isaacpitwa** [arnaudelub/flutter_fullpdfview#3]
Vertical scroll working fine on android but turns to horizontal scroll on IOS.

` PDFView(`
            `filePath: widget.path,`
            ` fitEachPage: true,`
            `dualPageMode: true,`
            `enableSwipe: true,`
            `swipeHorizontal: false,`
            `autoSpacing: false,`
            `pageFling: true,`
            `defaultPage: 1,`
            `pageSnap: true,`
            `onRender: (_pages) {`
             ` print("OK RENDERED!!!!!");`
              `setState(() {`
                `pages = _pages;`
               ` isReady = true;`
             ` });`
            `},`
            `onError: (error) {`
              `setState(() {`
               ` errorMessage = error.toString();`
              `});`
              `print(error.toString());`
            `},`
            `onPageError: (page, error) {`
              `setState(() {`
                `errorMessage = '$page: ${error.toString()}';`
             ` });`
              `print('$page: ${error.toString()}');`
            `},`
            `onViewCreated: (PDFViewController pdfViewController) {`
              `_controller.complete(pdfViewController);`
            `},`
            `onPageChanged: (int page, int total) {`
              `print('page change: $page/$total');`
            `},`
          `)`

**Comment by arnaudelub** [comment]
Hi,
thanks for reporting, fix has been published, please use version 1.0.3+2.
Let me know if you have more issues on this matter

**Comment by isaacpitwa** [comment]
> Hi,
> thanks for reporting, fix has been published, please use version 1.0.3+2.
> Let me know if you have more issues on this matter

How do I get to start on first-page **Cover page**
 using `defaultPage:1` does not work?

**Comment by arnaudelub** [comment]
try defaultPage:0
