### ISSUE TITLE
How can I show last opened page after configuration change?

### ISSUE THREAD

**Issue by JantuDeb** [arnaudelub/flutter_fullpdfview#6]
If you add an example how to use PdfViewControllar class and it's method, it will help.
Is it possible to add spacing between two Pages, Since auto spacing add big Margin.
Thanks, this plugin is better than any other flutter pdf viewer plugin

**Comment by arnaudelub** [comment]
Have you checked the example app for the controller?
Spacing can be implemented, it has not been done yet.
For the last opened page, have you try to use defaultPage?

**Comment by JantuDeb** [comment]
I did checked. But didn't get it done. If it's possible for you then please add it to the example app.
