### ISSUE TITLE
Couldn't launch url from pdf.

### ISSUE THREAD

**Issue by JantuDeb** [arnaudelub/flutter_fullpdfview#7]
Application destroy when clicked on link.

**Comment by arnaudelub** [comment]
you need to download the pdf first, then write the bytes to a File then you'll be able to read the PDF.
You can use getApplicationDocumentsDirectory() from path_provider or get the temporary Directory.

**Comment by JantuDeb** [comment]
Sorry, I didn't mean it. Actually if there is link in the pdf, when I clicked on the linked app crashes

**Comment by arnaudelub** [comment]
ok, on iOS? , Android? Both?

**Comment by JantuDeb** [comment]
I'm working on Android only,

**Comment by arnaudelub** [comment]
ok thanks, i'll check on that as soon as i can

**Comment by EngDjango** [comment]
i'm facing this too, plz try to fix it, thank you for your good work;
## Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK ## flag. Is this really what you want?

**Comment by JantuDeb** [comment]
Hey, any progress on this issue?

**Comment by arnaudelub** [comment]
Hi guys, sorry to make you wait. Issue has been fixed and published with version 1.1.0 on pub.dev.
Thank you for your help!
